#!/usr/bin/env python3
"""Regenerate the Hazemoor Obsidian project-memory snapshot from the live repo.

Source of truth = the repository itself (git + file counts + spec slice headers).
This never edits hand-authored notes; it only overwrites the single generated
note `projects/Hazemoor/Repo Snapshot.md` in the vault.

Usage:
    python3 tools/obsidian_snapshot.py            # write snapshot
    python3 tools/obsidian_snapshot.py --print    # dry run to stdout
"""
from __future__ import annotations
import subprocess, sys, os, glob, datetime, re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]                       # godot-project/
SPECS = REPO / "specs" / "hazemoor"                              # production contracts
VAULT = Path("/mnt/e/Obsidian/Hazemoor Vault")
OUT = VAULT / "projects" / "Hazemoor" / "Repo Snapshot.md"


def sh(cmd: str, cwd: Path = REPO) -> str:
    try:
        return subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True,
                              text=True, timeout=60).stdout.strip()
    except Exception as e:
        return f"(error: {e})"


def count(pattern: str, base: Path = REPO) -> int:
    return len(glob.glob(str(base / pattern), recursive=True))


def slice_statuses() -> list[tuple[str, str]]:
    rows = []
    for f in sorted(glob.glob(str(SPECS / "slices/*.md"))):
        name = os.path.basename(f).replace(".md", "")
        status = "?"
        try:
            txt = Path(f).read_text(encoding="utf-8", errors="replace")
            m = re.search(r"\*\*Status:\*\*\s*(.+)", txt)
            if m:
                status = m.group(1).strip()
        except Exception:
            pass
        rows.append((name, status))
    return rows


def build() -> str:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    head = sh("git rev-parse --short HEAD")
    head_msg = sh("git log -1 --format='%s (%cd)' --date=short")
    branch = sh("git rev-parse --abbrev-ref HEAD")
    dirty = sh("git status --short")
    dirty_n = len([l for l in dirty.splitlines() if l.strip()])
    recent = sh("git log -8 --format='- `%h` %s (%cd)' --date=short")

    counts = {
        "Quests": count("data/quests/*.json"),
        "Scenes (.tscn)": count("scenes/**/*.tscn"),
        "Dialogues": count("data/dialogues/**/*.json"),
        "NPC data": count("data/npcs/*.json"),
        "Gameplay scripts": count("scripts/gameplay/*.gd"),
        "Core scripts": count("scripts/core/*.gd"),
        "Meshy GLB models": count("assets/meshy/**/*.glb"),
    }

    lines = [
        "---",
        "generated: true",
        f"updated: {now}",
        "tags: [hazemoor, snapshot, generated]",
        "note: DO NOT EDIT BY HAND — regenerated by tools/obsidian_snapshot.py",
        "---",
        "",
        "# Hazemoor — Repo Snapshot (auto)",
        "",
        f"> [!info] Згенеровано {now}. Джерело істини — репозиторій, не ця нотатка.",
        f"> Оновити: `python3 tools/obsidian_snapshot.py` з `godot-project/`.",
        "",
        "## Git",
        f"- **Branch:** `{branch}`",
        f"- **HEAD:** `{head}` — {head_msg}",
        f"- **Uncommitted files:** {dirty_n}",
        "",
        "### Recent commits",
        recent or "(none)",
        "",
        "## Content counts",
        "| Артефакт | К-сть |",
        "|---|---|",
    ]
    for k, v in counts.items():
        lines.append(f"| {k} | {v} |")

    lines += ["", "## Canonical slices", "| Slice | Статус |", "|---|---|"]
    for name, status in slice_statuses():
        lines.append(f"| {name} | {status} |")

    lines += ["", "## Uncommitted worktree"]
    if dirty_n:
        lines.append("```")
        lines += dirty.splitlines()[:60]
        if dirty_n > 60:
            lines.append(f"... (+{dirty_n - 60} more)")
        lines.append("```")
    else:
        lines.append("_Clean._")

    lines += ["", "---", "See also: [[_Hub]] · [[Architecture]] · [[Canon & Slices]] · [[Decisions]] · [[Gotchas]]", ""]
    return "\n".join(lines)


def main() -> None:
    content = build()
    if "--print" in sys.argv:
        print(content)
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
